function [ c ] = splineCoeffPeriodic( y, m )
k=floor(m/2);
n=length(y);
%Bm = toeplitz([bSpline(0,m),bSpline(1:k,m),zeros(1,n-2*k-1),bSpline(-(k:-1:1),m)],...
%     [bSpline(0,m),bSpline(-(1:k),m),zeros(1,n-2*k-1),bSpline(k:-1:1,m)]);
Bm = toeplitz(...
  [bSpline(0,m),bSpline(1:k,m),zeros(1,n-2*k-1),...
      bSpline(-(k:-1:1),m)],...
  [bSpline(0,m),bSpline(-(1:k),m),...
      zeros(1,n-2*k-1),bSpline(k:-1:1,m)]);
ca=Bm\y;
c=[ca(n-(k:-1:1));ca;ca((1:k)+1)];
end